/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserPlaylistsPlaylistIdRouteImport } from './routes/user-playlists.$playlistId'
import { Route as PlaylistsPlaylistIdRouteImport } from './routes/playlists.$playlistId'
import { Route as ArtistsArtistIdRouteImport } from './routes/artists.$artistId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPlaylistsPlaylistIdRoute = UserPlaylistsPlaylistIdRouteImport.update({
  id: '/user-playlists/$playlistId',
  path: '/user-playlists/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsPlaylistIdRoute = PlaylistsPlaylistIdRouteImport.update({
  id: '/playlists/$playlistId',
  path: '/playlists/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsArtistIdRoute = ArtistsArtistIdRouteImport.update({
  id: '/artists/$artistId',
  path: '/artists/$artistId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/user-playlists/$playlistId': typeof UserPlaylistsPlaylistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/user-playlists/$playlistId': typeof UserPlaylistsPlaylistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/user-playlists/$playlistId': typeof UserPlaylistsPlaylistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artists/$artistId'
    | '/playlists/$playlistId'
    | '/user-playlists/$playlistId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artists/$artistId'
    | '/playlists/$playlistId'
    | '/user-playlists/$playlistId'
  id:
    | '__root__'
    | '/'
    | '/artists/$artistId'
    | '/playlists/$playlistId'
    | '/user-playlists/$playlistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistsArtistIdRoute: typeof ArtistsArtistIdRoute
  PlaylistsPlaylistIdRoute: typeof PlaylistsPlaylistIdRoute
  UserPlaylistsPlaylistIdRoute: typeof UserPlaylistsPlaylistIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-playlists/$playlistId': {
      id: '/user-playlists/$playlistId'
      path: '/user-playlists/$playlistId'
      fullPath: '/user-playlists/$playlistId'
      preLoaderRoute: typeof UserPlaylistsPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$playlistId': {
      id: '/playlists/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof PlaylistsPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$artistId': {
      id: '/artists/$artistId'
      path: '/artists/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof ArtistsArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistsArtistIdRoute: ArtistsArtistIdRoute,
  PlaylistsPlaylistIdRoute: PlaylistsPlaylistIdRoute,
  UserPlaylistsPlaylistIdRoute: UserPlaylistsPlaylistIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
